version: '3.7'

volumes:
    pgdata:

services: 
    postgres:
        image:  postgres:12-alpine
        command: postgres -c log_connections=on -c log_disconnections=on #-c log_statement=all
        restart: always
        env_file: 
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports: 
            - "8080:5432"

    api:
        build: .

        depends_on: 
            - tcpdump
            - postgres
        network_mode: "service:tcpdump"

    tcpdump:
        build:
            context: .
            dockerfile: dockerfile-tcpdump
        volumes:
            - type: bind
              source: /leashed/pcap
              target: /pcap
        ports:
            - "5001:5001"
            - "5000:5000"
        
