version: '3.7'

volumes:
    pgdata:

services: 
    postgres:
        image:  postgres:12-alpine
        container_name: leashapi_postgres_1
        command: postgres -c log_connections=on -c log_disconnections=on
        restart: always
        env_file: 
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports: 
            - "8080:5432"

    api:
        build: .
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "5001:5001"
            - "5000:5000"
        depends_on: 
            - postgres
