version: '3.7'

volumes:
    pgdata:

services: 
    postgres:
        build:
            context: .
            dockerfile: Dockerfile-postgres
        container_name: leashapi_postgres_1
        command:  >
            postgres -c log_connections=on -c log_disconnections=on -c ssl=on 
            -c ssl_cert_file=/var/lib/postgresql/server.crt 
            -c ssl_key_file=/var/lib/postgresql/server.key

        restart: always
        env_file: 
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports: 
            - "8080:5432"

    api:
        build: .
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
            - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
        ports:
            - "5001:5001"
            - "5000:5000"
        depends_on: 
            - postgres
