name: CI

on:  
  push:
    branches: 
      - master
      - release/*

jobs:
  build_leashapi:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image and deploy to heroku
      env:
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
       APP_NAME: ${{ 'leashapi' }}
      run: |
        cd ./ASPNetCoreLabs/HerokuContainer
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
      

